//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplaintManagementPortal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string YourComplaint { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> WorkId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string MainImage { get; set; }
        public string UserId { get; set; }
        public bool SendmeEmails { get; set; }
    
        public virtual ComplaintsStatus ComplaintsStatus { get; set; }
        public virtual GenderType GenderType { get; set; }
        public virtual WorkType WorkType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
